

<!-- Subhead
================================================== -->
<header >

</header>

  <div class="container" >

    <div class="row" id="core" >

    </div>

  </div>

    <!-- Footer
    ================================================== -->
    <footer class="footer">
      <div class="container">
        <p><a href="http://www.phox.loc" target="_new" >Déconnexion</a></p>
      </div>
    </footer>



   
