<div id="grid">
    <phx:TPlugin id="accordion0"  pattern="accordion" pivot="false" command="var:cmd" children="var:items" rowCount="var:pageCount" pageNum="var:index" >
        <phx:TPluginChild id="items" name="Year" enabled="true" />
        <phx:TPluginChild id="items" name="ArtistId" enabled="false" />
        <phx:TPluginChild id="items" name="Artist" content="@artistItem.phtml" enabled="false" event="href#home.showArtist(Artist)" />
        <phx:TPluginChild id="items" name="AlbumId" enabled="false" />
        <phx:TPluginChild id="items" name="Album" content="@albumItem.phtml" enabled="true" event="href#home.showAlbum(Artist)" />
        <phx:TPluginChild id="items" name="TitleId" enabled="false" />
        <phx:TPluginChild id="items" name="Title" content="@titleItem.phtml" dragHelper="@titleDragged.phtml" enabled="true" event="href#home.showTitle(TitleId)" />
    </phx:TPlugin>
</div>
<phx:TPager id="pager" for="accordion0" caption="Albums de ma musique"  onclick="home.getData"  />
