version: "3.0"
services:
  mysql:
    build: ./docker/cabane/mysql
    image: mysql:solight
    environment:
     - MYSQL_ROOT_PASSWORD=solight
    ports:
     - "3306:3306"
    volumes:
     - my_data:/var/lib/mysql
     - ./src/data:/data

  php:
    build: ./docker/cabane/php7
    image: php:7-pdo
    volumes:
     - ./src:/sites/sol
     - ./admin:/sites/ladmin
     - ./docker/cabane/php.ini:/usr/local/etc/php/conf.d/customizations.ini
     - ../Phink/src/phink:/usr/local/lib/php/phink
    links:
     - mysql:db

  web:
    hostname: sol.loc
    image: nginx:latest
    ports:
     - "80:80"
     - "443:443"
    volumes:
     - ./src:/sites/sol
     - ./src/web/nginx.conf:/etc/nginx/conf.d/default.conf
     - ../Phink/src/phink:/usr/local/lib/php/phink
    links:
     - php:php
     - mysql:db

  admin:
    hostname: ladmin.loc
    image: nginx:latest
    ports:
     - "8080:8080"
     - "8443:443"
    volumes:
     - ./admin:/sites/ladmin
     - ./admin/web/nginx.conf:/etc/nginx/conf.d/default.conf
     - ../Phink/src/phink:/usr/local/lib/php/phink
    links:
     - php:php
     - mysql:db

  api:
    hostname: soundlib.loc
    build: ./docker/cabane/node
    image: node:cabane
    ports:
     - "1234:1234"
     - "4043:443"
     - "8088:80"
    volumes:
     - ./api:/site
    links:
     - mysql:db

volumes:
  my_data:

