<div class="container-fluid">
    <div class="row-fluid">
        <div class="page-header">
            <phx:Dummy id="dummy" />
        </div>
    </div>
        <!--left-->
        <div class="col-sm-3">
            <phx:Grid id="grid0" anchor="#grid" pageCount="10" />
        </div><!--/left-->

        <!--center-->
        <div class="col-sm-6">
            <div id="wikipedia" width="100%" height="100%" frameborder="0" 
                    style="overflow: scroll; height: 960px; width: 100%; position: relative;">
            </div>
            <!--onload="TUtils.resizeIframe(this)"-->
        </div><!--/center-->

        <!--right-->
        <div class="col-sm-3 ">
            <h2>Playlist</h2>
            <div id="dropper" >
                <h1> DROP HERE </h1>
            </div>
            <hr>
        </div><!--/right-->
        <hr>        
<div id="token" class="panel panel-default">
</div>
</div>
