<div class="container-fluid">
    <div class="row-fluid">
        <div class="page-header player">
            <phx:Dummy id="dummy" />
        </div>
    </div>
    <!--left-->
    <div class="col-sm-3 scroll_container collection" >
        <phx:Collection id="collection0" anchor="#collection" />
    </div><!--/left-->

    <!--center-->
    <div class="col-sm-6 scroll_container mediaspace">
        <div id="wikipedia" frameborder="0" class="scroll_mediaspace">
        </div>
        <!--onload="TUtils.resizeIframe(this)"-->
    </div><!--/center-->

    <!--right-->
    <div class="col-sm-3 playlist" >
        <span>Playlist</span>
        <div id="dropper" class="scroll_container " >
            <phx:Playlist id="playlist0" anchor="#playlist" />
        </div>
        <hr>
    </div><!--/right-->
    <hr>        
    <div id="token" class="panel panel-default">
    </div>
</div>
