<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <title>TODO supply a title</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script src="https://secure.aadcdn.microsoftonline-p.com/lib/1.0.12/js/adal.min.js"></script>        
    </head>
    <body>
        <div>TODO write content</div>
        <button id="SignIn" onclick="signIn()">Sign In</button>
        <h4 id="WelcomeMessage"></h4>        
    </body>
</html>
