<div class="container-fluid">
    <div class="row-fluid">
        <div class="span3">


        </div>
        <div class="span9">
    <!-- Modal
    ================================================== -->
            <section id="modals">
            <div class="page-header">
                <h1>Accueil <small>des visiteurs</small></h1>
            </div>

            <div>
                <phx:Dummy id="dummy" />
            </div>
            <div>
                <phx:Grid id="grid0" />
            </div>

            <div id="token">

            </div>


            </section>

        </div>
    </div>
</div>

<script type="text/javascript" >
    showToken();
</script>
