<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

echo base64_decode("PD9waHAKXFBoaW5rXFRBdXRvbG9hZGVyOjppbXBvcnQoJHRoaXMsICJEdW1teSIpOwpcUGhpbmtcVEF1dG9sb2FkZXI6OmltcG9ydCgkdGhpcywgIkFiY0FydGlzdHMiKTsKXFBoaW5rXFRBdXRvbG9hZGVyOjppbXBvcnQoJHRoaXMsICJBYmNBbGJ1bXMiKTsKXFBoaW5rXFRBdXRvbG9hZGVyOjppbXBvcnQoJHRoaXMsICJBYmNZZWFycyIpOwoKJHRoaXMtPnNldElkKCJob21lIik7IAokdGhpcy0+ZHVtbXkgPSBuZXcgXCgkdGhpcyk7IAokdGhpcy0+ZHVtbXktPnNldElkKCJkdW1teSIpOyAKJHRoaXMtPmFiY0FydGlzdHMgPSBuZXcgXCgkdGhpcyk7IAokdGhpcy0+YWJjQXJ0aXN0cy0+c2V0SWQoImFiY0FydGlzdHMiKTsgCiR0aGlzLT5hYmNBbGJ1bXMgPSBuZXcgXCgkdGhpcyk7IAokdGhpcy0+YWJjQWxidW1zLT5zZXRJZCgiYWJjQWxidW1zIik7IAokdGhpcy0+YWJjWWVhcnMgPSBuZXcgXCgkdGhpcyk7IAokdGhpcy0+YWJjWWVhcnMtPnNldElkKCJhYmNZZWFycyIpOyAKPz4=");