<div class="container-fluid">
    <div class="row-fluid">
        <div class="page-header">
            <phx:Dummy id="dummy" />
        </div>
    </div>
        <!--left-->
        <div class="col-sm-3">
            <div id="dataGrid" >
                <div id="grid">
                    <phx:Grid id="grid0" anchor="#grid" pageCount="20" />
                </div>
                <phx:TPager id="pager" for="grid0" caption="Albums de ma musique"  onclick="home.getData" pageCount="20" />
            </div>
        </div><!--/left-->

        <!--center-->
        <div class="col-sm-6">
            <div class="row">
                <div id="vikipedia" class="col-xs-12">
                </div>
            </div>
            <hr>
            <hr>
        </div><!--/center-->

        <!--right-->
        <div class="col-sm-3">
            <h2>Side</h2>

            <div id="token" class="panel panel-default">

            </div>
            <hr>

        </div><!--/right-->
        <hr>        
</div>
