
    <form class="form-signin" >
        <h2 class="form-signin-heading">Code Ph&oelig;nix (&alpha;lph&alpha;)</h2>
      <input class="form-control" type="text" id="login" name="login" placeholder="Identifiant" value="lambda">
      <input class="form-control" type="password" id="password" name="password" placeholder="Mot de passe" value="1MF14m2p97">
      <button class="btn btn-lg btn-primary  btn-block" type="button" name="valider" value="ok" onclick="authenticate();" >Valider</button>
      <div id="message" style="color: red;">
      </div>
    </form>

