
<!DOCTYPE html>
<html lang="en" debug="true" >
    <head>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8">
        <meta charset="utf-8">
        <title>Sound Of Light</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

        <meta name="description" content="">
        <meta name="author" content="">

        <link href="css/_3rdparty.css" rel="stylesheet">
        <link href="css/full-slider.css" rel="stylesheet">
        <link href="css/wikipedia.css" rel="stylesheet">
        <link href="css/sol.css" rel="stylesheet">

        <script type="text/javascript" 
                data-depends="js/_3rdparty.js" 
                data-sources="js/debug.js" 
                src="/phink.js">
        </script>
    </head>
    <body data-twttr-rendered="true" data-spy="scroll" >
        <div id='body'>
        <form class="form-signin" >
    <input type="hidden" id="login" name="login" value="lambda">
    <h2 class="form-signin-heading">Sound Of Light (&alpha;lph&alpha;)</h2>
    <input class="form-control" type="text" id="login" name="login" placeholder="Identifiant" value="lambda">
    <input class="form-control" type="password" id="password" name="password" placeholder="Mot de passe" value="1MF14m2p97">
    <button class="btn btn-lg btn-primary  btn-block" type="button" name="valider" value="ok" id="authenticate" >Valider</button>
    <div id="message" style="color: red;">
    </div>
</form>
<div>
    <phx:echo var="headers" />
</div>

        </div>


    </body>
</html>

