<!DOCTYPE html>
<html lang="en" debug="true" >
    <head>
        <meta charset="utf-8">
        <title>Sound Of Light</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

        <meta name="description" content="">
        <meta name="author" content="">

        <link href="css/_3rdparty.css" rel="stylesheet">
        <link href="css/full-slider.css" rel="stylesheet">
        <link href="css/wikipedia.css" rel="stylesheet">
        <link href="css/sol.css" rel="stylesheet">
        <!-- http://ladmin.loc/js/access.js; -->
        <!-- js/debug.js"  -->

        <script type="text/javascript" 
                data-depends="js/_3rdparty.js;js/sol.js" 
                data-sources="js/sol_runtime.js;"
                src="/phink.js">
        </script>
    </head>
    <body data-twttr-rendered="true" data-spy="scroll" >
    </body>
</html>