<div id="playlist" style="height: 100%; overflow: hidden;" class="mCustomScrollbar" >
    <phx:TPlugin id="list0"  pattern="ulli" pivot="false" command="var:cmd" children="var:items" rowCount="var:pageCount" pageNum="var:index" >
        <phx:TPluginChild id="items" name="pid" enabled="false" />
        <phx:TPluginChild id="items" name="id" enabled="false" />
        <phx:TPluginChild id="items" name="ArtistId" enabled="false" />
        <phx:TPluginChild id="items" name="Artist" enabled="false"  />
        <phx:TPluginChild id="items" name="TitleId" enabled="false" />
        <phx:TPluginChild id="items" name="Title" content="@playlistTrack.phtml"  enabled="true" event="href#solPlayer.pl.removeTrack(id)" />
        <phx:TPluginChild id="items" name="Duration" enabled="false" />
        <phx:TPluginChild id="items" name="TrackPath" enabled="false" />
    </phx:TPlugin>
    <!--phx:TPager id="pager" for="accordion0" caption="Albums de ma musique"  onclick="solPlayer.getData"  /-->
</div>
