
<form class="form-signin" >
    <input type="hidden" id="login" name="login" value="lambda">
    <h2 class="form-signin-heading">Sound Of Light (&alpha;lph&alpha;)</h2>
    <input class="form-control" type="text" id="login" name="login" placeholder="Identifiant" value="lambda">
    <input class="form-control" type="password" id="password" name="password" placeholder="Mot de passe" value="1MF14m2p97">
    <button class="btn btn-lg btn-primary  btn-block" type="button" name="valider" value="ok" id="authenticate" >Valider</button>
    <div id="message" style="color: red;">
    </div>
</form>
<div>
    <phx:echo var="headers" />
</div>

