#!/bin/bash
pwd

echo > logs/debug.log
find runtime -type f -exec rm -f {} \; 
find web/js/runtime -type f -exec rm -f {} \; 
find cache/main_html_artist_*; 
echo "All logs and temporary files cleared at "$(date) 
